(cl:defpackage vlmap_msgs-srv
  (:use )
  (:export
   "QUERYROOM"
   "<QUERYROOM-REQUEST>"
   "QUERYROOM-REQUEST"
   "<QUERYROOM-RESPONSE>"
   "QUERYROOM-RESPONSE"
   "RESOLVEROOM"
   "<RESOLVEROOM-REQUEST>"
   "RESOLVEROOM-REQUEST"
   "<RESOLVEROOM-RESPONSE>"
   "RESOLVEROOM-RESPONSE"
  ))

