# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from vlmap_msgs/SemanticGoal.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class SemanticGoal(genpy.Message):
  _md5sum = "5ad7085f3396999b2c42c4f499c94bef"
  _type = "vlmap_msgs/SemanticGoal"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# Goal expressed in semantic terms (mirror of src/tfg_nav_contracts/SemanticGoal).
#
# Field semantics:
#   type          one of: ROOM, APPROACH, INSPECT, VERIFY (string for clarity)
#   map_pose      goal pose in the /map frame
#   room_id       room label assigned by the room labeler ("kitchen", ...)
#   object_class  target category for verification ("sofa", "bottle", ...)
#   metadata      free-form JSON string with extra context (priors, etc.)
string type
geometry_msgs/PoseStamped map_pose
string room_id
string object_class
string metadata

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['type','map_pose','room_id','object_class','metadata']
  _slot_types = ['string','geometry_msgs/PoseStamped','string','string','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       type,map_pose,room_id,object_class,metadata

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(SemanticGoal, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.type is None:
        self.type = ''
      if self.map_pose is None:
        self.map_pose = geometry_msgs.msg.PoseStamped()
      if self.room_id is None:
        self.room_id = ''
      if self.object_class is None:
        self.object_class = ''
      if self.metadata is None:
        self.metadata = ''
    else:
      self.type = ''
      self.map_pose = geometry_msgs.msg.PoseStamped()
      self.room_id = ''
      self.object_class = ''
      self.metadata = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.map_pose.header.seq, _x.map_pose.header.stamp.secs, _x.map_pose.header.stamp.nsecs))
      _x = self.map_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.map_pose.pose.position.x, _x.map_pose.pose.position.y, _x.map_pose.pose.position.z, _x.map_pose.pose.orientation.x, _x.map_pose.pose.orientation.y, _x.map_pose.pose.orientation.z, _x.map_pose.pose.orientation.w))
      _x = self.room_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.metadata
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.map_pose is None:
        self.map_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.map_pose.header.seq, _x.map_pose.header.stamp.secs, _x.map_pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.map_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.map_pose.pose.position.x, _x.map_pose.pose.position.y, _x.map_pose.pose.position.z, _x.map_pose.pose.orientation.x, _x.map_pose.pose.orientation.y, _x.map_pose.pose.orientation.z, _x.map_pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.room_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.room_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_class = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.metadata = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.map_pose.header.seq, _x.map_pose.header.stamp.secs, _x.map_pose.header.stamp.nsecs))
      _x = self.map_pose.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_7d().pack(_x.map_pose.pose.position.x, _x.map_pose.pose.position.y, _x.map_pose.pose.position.z, _x.map_pose.pose.orientation.x, _x.map_pose.pose.orientation.y, _x.map_pose.pose.orientation.z, _x.map_pose.pose.orientation.w))
      _x = self.room_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.object_class
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.metadata
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.map_pose is None:
        self.map_pose = geometry_msgs.msg.PoseStamped()
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.map_pose.header.seq, _x.map_pose.header.stamp.secs, _x.map_pose.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.map_pose.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.map_pose.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 56
      (_x.map_pose.pose.position.x, _x.map_pose.pose.position.y, _x.map_pose.pose.position.z, _x.map_pose.pose.orientation.x, _x.map_pose.pose.orientation.y, _x.map_pose.pose.orientation.z, _x.map_pose.pose.orientation.w,) = _get_struct_7d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.room_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.room_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.object_class = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.object_class = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.metadata = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.metadata = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
