// Generated by gencpp from file vlmap_msgs/QueryRoomResponse.msg
// DO NOT EDIT!


#ifndef VLMAP_MSGS_MESSAGE_QUERYROOMRESPONSE_H
#define VLMAP_MSGS_MESSAGE_QUERYROOMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vlmap_msgs
{
template <class ContainerAllocator>
struct QueryRoomResponse_
{
  typedef QueryRoomResponse_<ContainerAllocator> Type;

  QueryRoomResponse_()
    : rooms()
    , scores()  {
    }
  QueryRoomResponse_(const ContainerAllocator& _alloc)
    : rooms(_alloc)
    , scores(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>> _rooms_type;
  _rooms_type rooms;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _scores_type;
  _scores_type scores;





  typedef boost::shared_ptr< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct QueryRoomResponse_

typedef ::vlmap_msgs::QueryRoomResponse_<std::allocator<void> > QueryRoomResponse;

typedef boost::shared_ptr< ::vlmap_msgs::QueryRoomResponse > QueryRoomResponsePtr;
typedef boost::shared_ptr< ::vlmap_msgs::QueryRoomResponse const> QueryRoomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator1> & lhs, const ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator2> & rhs)
{
  return lhs.rooms == rhs.rooms &&
    lhs.scores == rhs.scores;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator1> & lhs, const ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vlmap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ed3772818fc622ee82ba797ed36e139f";
  }

  static const char* value(const ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xed3772818fc622eeULL;
  static const uint64_t static_value2 = 0x82ba797ed36e139fULL;
};

template<class ContainerAllocator>
struct DataType< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vlmap_msgs/QueryRoomResponse";
  }

  static const char* value(const ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] rooms\n"
"float32[] scores\n"
"\n"
;
  }

  static const char* value(const ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.rooms);
      stream.next(m.scores);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryRoomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vlmap_msgs::QueryRoomResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "rooms: ";
    if (v.rooms.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.rooms.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, true ? std::string() : indent + "    ", v.rooms[i]);
    }
    if (v.rooms.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "scores: ";
    if (v.scores.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.scores.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<float>::stream(s, true ? std::string() : indent + "    ", v.scores[i]);
    }
    if (v.scores.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLMAP_MSGS_MESSAGE_QUERYROOMRESPONSE_H
