// Generated by gencpp from file vlmap_msgs/QueryRoom.msg
// DO NOT EDIT!


#ifndef VLMAP_MSGS_MESSAGE_QUERYROOM_H
#define VLMAP_MSGS_MESSAGE_QUERYROOM_H

#include <ros/service_traits.h>


#include <vlmap_msgs/QueryRoomRequest.h>
#include <vlmap_msgs/QueryRoomResponse.h>


namespace vlmap_msgs
{

struct QueryRoom
{

typedef QueryRoomRequest Request;
typedef QueryRoomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryRoom
} // namespace vlmap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vlmap_msgs::QueryRoom > {
  static const char* value()
  {
    return "dd7014894137ba2b5c36b11fca65c3bb";
  }

  static const char* value(const ::vlmap_msgs::QueryRoom&) { return value(); }
};

template<>
struct DataType< ::vlmap_msgs::QueryRoom > {
  static const char* value()
  {
    return "vlmap_msgs/QueryRoom";
  }

  static const char* value(const ::vlmap_msgs::QueryRoom&) { return value(); }
};


// service_traits::MD5Sum< ::vlmap_msgs::QueryRoomRequest> should match
// service_traits::MD5Sum< ::vlmap_msgs::QueryRoom >
template<>
struct MD5Sum< ::vlmap_msgs::QueryRoomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vlmap_msgs::QueryRoom >::value();
  }
  static const char* value(const ::vlmap_msgs::QueryRoomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vlmap_msgs::QueryRoomRequest> should match
// service_traits::DataType< ::vlmap_msgs::QueryRoom >
template<>
struct DataType< ::vlmap_msgs::QueryRoomRequest>
{
  static const char* value()
  {
    return DataType< ::vlmap_msgs::QueryRoom >::value();
  }
  static const char* value(const ::vlmap_msgs::QueryRoomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vlmap_msgs::QueryRoomResponse> should match
// service_traits::MD5Sum< ::vlmap_msgs::QueryRoom >
template<>
struct MD5Sum< ::vlmap_msgs::QueryRoomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vlmap_msgs::QueryRoom >::value();
  }
  static const char* value(const ::vlmap_msgs::QueryRoomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vlmap_msgs::QueryRoomResponse> should match
// service_traits::DataType< ::vlmap_msgs::QueryRoom >
template<>
struct DataType< ::vlmap_msgs::QueryRoomResponse>
{
  static const char* value()
  {
    return DataType< ::vlmap_msgs::QueryRoom >::value();
  }
  static const char* value(const ::vlmap_msgs::QueryRoomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VLMAP_MSGS_MESSAGE_QUERYROOM_H
