// Generated by gencpp from file vlmap_msgs/QueryRoomRequest.msg
// DO NOT EDIT!


#ifndef VLMAP_MSGS_MESSAGE_QUERYROOMREQUEST_H
#define VLMAP_MSGS_MESSAGE_QUERYROOMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vlmap_msgs
{
template <class ContainerAllocator>
struct QueryRoomRequest_
{
  typedef QueryRoomRequest_<ContainerAllocator> Type;

  QueryRoomRequest_()
    : category()  {
    }
  QueryRoomRequest_(const ContainerAllocator& _alloc)
    : category(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _category_type;
  _category_type category;





  typedef boost::shared_ptr< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct QueryRoomRequest_

typedef ::vlmap_msgs::QueryRoomRequest_<std::allocator<void> > QueryRoomRequest;

typedef boost::shared_ptr< ::vlmap_msgs::QueryRoomRequest > QueryRoomRequestPtr;
typedef boost::shared_ptr< ::vlmap_msgs::QueryRoomRequest const> QueryRoomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator1> & lhs, const ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator2> & rhs)
{
  return lhs.category == rhs.category;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator1> & lhs, const ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vlmap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7397d5563c5bad7f8044755b463842e8";
  }

  static const char* value(const ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7397d5563c5bad7fULL;
  static const uint64_t static_value2 = 0x8044755b463842e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vlmap_msgs/QueryRoomRequest";
  }

  static const char* value(const ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Ask the semantic server which rooms most likely contain a category.\n"
"#\n"
"# Request:\n"
"#   category  free text label, e.g. \"sofa\", \"bottle\".\n"
"# Response:\n"
"#   rooms     ordered list of room ids, best first.\n"
"#   scores    matching list of priors / scores for each room.\n"
"string category\n"
;
  }

  static const char* value(const ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.category);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct QueryRoomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vlmap_msgs::QueryRoomRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "category: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.category);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLMAP_MSGS_MESSAGE_QUERYROOMREQUEST_H
