// Generated by gencpp from file vlmap_msgs/ResolveRoom.msg
// DO NOT EDIT!


#ifndef VLMAP_MSGS_MESSAGE_RESOLVEROOM_H
#define VLMAP_MSGS_MESSAGE_RESOLVEROOM_H

#include <ros/service_traits.h>


#include <vlmap_msgs/ResolveRoomRequest.h>
#include <vlmap_msgs/ResolveRoomResponse.h>


namespace vlmap_msgs
{

struct ResolveRoom
{

typedef ResolveRoomRequest Request;
typedef ResolveRoomResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ResolveRoom
} // namespace vlmap_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::vlmap_msgs::ResolveRoom > {
  static const char* value()
  {
    return "db7b5f5b60012129daeee10be8237c87";
  }

  static const char* value(const ::vlmap_msgs::ResolveRoom&) { return value(); }
};

template<>
struct DataType< ::vlmap_msgs::ResolveRoom > {
  static const char* value()
  {
    return "vlmap_msgs/ResolveRoom";
  }

  static const char* value(const ::vlmap_msgs::ResolveRoom&) { return value(); }
};


// service_traits::MD5Sum< ::vlmap_msgs::ResolveRoomRequest> should match
// service_traits::MD5Sum< ::vlmap_msgs::ResolveRoom >
template<>
struct MD5Sum< ::vlmap_msgs::ResolveRoomRequest>
{
  static const char* value()
  {
    return MD5Sum< ::vlmap_msgs::ResolveRoom >::value();
  }
  static const char* value(const ::vlmap_msgs::ResolveRoomRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::vlmap_msgs::ResolveRoomRequest> should match
// service_traits::DataType< ::vlmap_msgs::ResolveRoom >
template<>
struct DataType< ::vlmap_msgs::ResolveRoomRequest>
{
  static const char* value()
  {
    return DataType< ::vlmap_msgs::ResolveRoom >::value();
  }
  static const char* value(const ::vlmap_msgs::ResolveRoomRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::vlmap_msgs::ResolveRoomResponse> should match
// service_traits::MD5Sum< ::vlmap_msgs::ResolveRoom >
template<>
struct MD5Sum< ::vlmap_msgs::ResolveRoomResponse>
{
  static const char* value()
  {
    return MD5Sum< ::vlmap_msgs::ResolveRoom >::value();
  }
  static const char* value(const ::vlmap_msgs::ResolveRoomResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::vlmap_msgs::ResolveRoomResponse> should match
// service_traits::DataType< ::vlmap_msgs::ResolveRoom >
template<>
struct DataType< ::vlmap_msgs::ResolveRoomResponse>
{
  static const char* value()
  {
    return DataType< ::vlmap_msgs::ResolveRoom >::value();
  }
  static const char* value(const ::vlmap_msgs::ResolveRoomResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // VLMAP_MSGS_MESSAGE_RESOLVEROOM_H
