// Generated by gencpp from file vlmap_msgs/ResolveRoomResponse.msg
// DO NOT EDIT!


#ifndef VLMAP_MSGS_MESSAGE_RESOLVEROOMRESPONSE_H
#define VLMAP_MSGS_MESSAGE_RESOLVEROOMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vlmap_msgs
{
template <class ContainerAllocator>
struct ResolveRoomResponse_
{
  typedef ResolveRoomResponse_<ContainerAllocator> Type;

  ResolveRoomResponse_()
    : found(false)
    , room_id()
    , x(0.0)
    , y(0.0)  {
    }
  ResolveRoomResponse_(const ContainerAllocator& _alloc)
    : found(false)
    , room_id(_alloc)
    , x(0.0)
    , y(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _found_type;
  _found_type found;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _room_id_type;
  _room_id_type room_id;

   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ResolveRoomResponse_

typedef ::vlmap_msgs::ResolveRoomResponse_<std::allocator<void> > ResolveRoomResponse;

typedef boost::shared_ptr< ::vlmap_msgs::ResolveRoomResponse > ResolveRoomResponsePtr;
typedef boost::shared_ptr< ::vlmap_msgs::ResolveRoomResponse const> ResolveRoomResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator1> & lhs, const ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator2> & rhs)
{
  return lhs.found == rhs.found &&
    lhs.room_id == rhs.room_id &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator1> & lhs, const ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vlmap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be97407ed30065a5f9e6923ae6c8fa60";
  }

  static const char* value(const ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe97407ed30065a5ULL;
  static const uint64_t static_value2 = 0xf9e6923ae6c8fa60ULL;
};

template<class ContainerAllocator>
struct DataType< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vlmap_msgs/ResolveRoomResponse";
  }

  static const char* value(const ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool found\n"
"string room_id\n"
"float32 x\n"
"float32 y\n"
"\n"
;
  }

  static const char* value(const ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.found);
      stream.next(m.room_id);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResolveRoomResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vlmap_msgs::ResolveRoomResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "found: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.found);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "room_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.room_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLMAP_MSGS_MESSAGE_RESOLVEROOMRESPONSE_H
