// Generated by gencpp from file vlmap_msgs/ResolveRoomRequest.msg
// DO NOT EDIT!


#ifndef VLMAP_MSGS_MESSAGE_RESOLVEROOMREQUEST_H
#define VLMAP_MSGS_MESSAGE_RESOLVEROOMREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vlmap_msgs
{
template <class ContainerAllocator>
struct ResolveRoomRequest_
{
  typedef ResolveRoomRequest_<ContainerAllocator> Type;

  ResolveRoomRequest_()
    : room()  {
    }
  ResolveRoomRequest_(const ContainerAllocator& _alloc)
    : room(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _room_type;
  _room_type room;





  typedef boost::shared_ptr< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ResolveRoomRequest_

typedef ::vlmap_msgs::ResolveRoomRequest_<std::allocator<void> > ResolveRoomRequest;

typedef boost::shared_ptr< ::vlmap_msgs::ResolveRoomRequest > ResolveRoomRequestPtr;
typedef boost::shared_ptr< ::vlmap_msgs::ResolveRoomRequest const> ResolveRoomRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator1> & lhs, const ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator2> & rhs)
{
  return lhs.room == rhs.room;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator1> & lhs, const ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vlmap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e497569192cccb82020c3a5c262721b9";
  }

  static const char* value(const ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe497569192cccb82ULL;
  static const uint64_t static_value2 = 0x020c3a5c262721b9ULL;
};

template<class ContainerAllocator>
struct DataType< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vlmap_msgs/ResolveRoomRequest";
  }

  static const char* value(const ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Resolve a room label into a concrete 2D goal in the /map frame.\n"
"#\n"
"# Request:\n"
"#   room  semantic room label or alias, e.g. \"kitchen\", \"office\".\n"
"# Response:\n"
"#   found    whether the room could be resolved\n"
"#   room_id  exact room label used internally by the provider\n"
"#   x        x coordinate in the /map frame (metres)\n"
"#   y        y coordinate in the /map frame (metres)\n"
"string room\n"
;
  }

  static const char* value(const ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.room);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ResolveRoomRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vlmap_msgs::ResolveRoomRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "room: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.room);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLMAP_MSGS_MESSAGE_RESOLVEROOMREQUEST_H
