// Generated by gencpp from file vlmap_msgs/SemanticGoal.msg
// DO NOT EDIT!


#ifndef VLMAP_MSGS_MESSAGE_SEMANTICGOAL_H
#define VLMAP_MSGS_MESSAGE_SEMANTICGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace vlmap_msgs
{
template <class ContainerAllocator>
struct SemanticGoal_
{
  typedef SemanticGoal_<ContainerAllocator> Type;

  SemanticGoal_()
    : type()
    , map_pose()
    , room_id()
    , object_class()
    , metadata()  {
    }
  SemanticGoal_(const ContainerAllocator& _alloc)
    : type(_alloc)
    , map_pose(_alloc)
    , room_id(_alloc)
    , object_class(_alloc)
    , metadata(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _map_pose_type;
  _map_pose_type map_pose;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _room_id_type;
  _room_id_type room_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _object_class_type;
  _object_class_type object_class;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _metadata_type;
  _metadata_type metadata;





  typedef boost::shared_ptr< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SemanticGoal_

typedef ::vlmap_msgs::SemanticGoal_<std::allocator<void> > SemanticGoal;

typedef boost::shared_ptr< ::vlmap_msgs::SemanticGoal > SemanticGoalPtr;
typedef boost::shared_ptr< ::vlmap_msgs::SemanticGoal const> SemanticGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vlmap_msgs::SemanticGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::vlmap_msgs::SemanticGoal_<ContainerAllocator1> & lhs, const ::vlmap_msgs::SemanticGoal_<ContainerAllocator2> & rhs)
{
  return lhs.type == rhs.type &&
    lhs.map_pose == rhs.map_pose &&
    lhs.room_id == rhs.room_id &&
    lhs.object_class == rhs.object_class &&
    lhs.metadata == rhs.metadata;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::vlmap_msgs::SemanticGoal_<ContainerAllocator1> & lhs, const ::vlmap_msgs::SemanticGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace vlmap_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ad7085f3396999b2c42c4f499c94bef";
  }

  static const char* value(const ::vlmap_msgs::SemanticGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ad7085f3396999bULL;
  static const uint64_t static_value2 = 0x2c42c4f499c94befULL;
};

template<class ContainerAllocator>
struct DataType< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vlmap_msgs/SemanticGoal";
  }

  static const char* value(const ::vlmap_msgs::SemanticGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Goal expressed in semantic terms (mirror of src/tfg_nav_contracts/SemanticGoal).\n"
"#\n"
"# Field semantics:\n"
"#   type          one of: ROOM, APPROACH, INSPECT, VERIFY (string for clarity)\n"
"#   map_pose      goal pose in the /map frame\n"
"#   room_id       room label assigned by the room labeler (\"kitchen\", ...)\n"
"#   object_class  target category for verification (\"sofa\", \"bottle\", ...)\n"
"#   metadata      free-form JSON string with extra context (priors, etc.)\n"
"string type\n"
"geometry_msgs/PoseStamped map_pose\n"
"string room_id\n"
"string object_class\n"
"string metadata\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::vlmap_msgs::SemanticGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.type);
      stream.next(m.map_pose);
      stream.next(m.room_id);
      stream.next(m.object_class);
      stream.next(m.metadata);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SemanticGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vlmap_msgs::SemanticGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vlmap_msgs::SemanticGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "map_pose: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.map_pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "room_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.room_id);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "object_class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.object_class);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "metadata: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.metadata);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VLMAP_MSGS_MESSAGE_SEMANTICGOAL_H
